### ISSUE TITLE
Issue with Exporting Polygon Annotations to YOLO Format

### ISSUE THREAD

**Issue by chen-ricky** [HumanSignal/label-studio-sdk#365]
## Description:
Hi there,

I’m encountering an issue when exporting polygon annotations from Label Studio to YOLO format. My task involves labeling polygons around objects (in this case, solar panels), and when I attempt to export the annotations, I receive the following error:

```bash
KeyError: 'points'
```

It seems that the export process is looking for a `points` key, which is expected for bounding box annotations, but the annotations I have are polygons. The converter appears to be trying to process the polygon annotations as if they were bounding boxes, leading to the error.

Here is a snippet of the labeling configuration used in my task:

```xml
<View>
  <Image name="image" value="$image" zoom="true"/>
  <PolygonLabels model_path="my/model/path.pt" name="label" toName="image" model_score_threshold="0.1" opacity="0.1">
    <Label value="panel" background="blue"/>
  </PolygonLabels>
</View>
```

Also, as you may guess from the above xml, I've made initial predictions for the images before start labeling.

## Expected Behavior:
I am looking to export the annotations in YOLO format, which expects bounding boxes with coordinates normalized to the image size. The polygons should be converted into bounding boxes before exporting.

## Current Behavior:
When exporting, the process fails because the export function tries to access the `points` key for polygons, but this key is not defined in the format expected for YOLO.

## Steps to Reproduce:
- Create a project with polygon annotations using the `<PolygonLabels>` tag.
- Attempt to export the data to YOLO format.
- Encounter the `KeyError: 'points' error`.
I’ve attached a screenshot showing the issue in case it helps in diagnosing the problem.

![Screenshot from 2024-12-04 11-39-47](https://github.com/user-attachments/assets/064256d6-f6c7-44c9-a5a1-c9533b401f68)

Is there a way to handle polygon annotations properly when exporting to YOLO format? Or would I need to implement a custom conversion function to transform polygons into bounding boxes?

Thanks for your help!

**Comment by rezakarbasi** [comment]
I've seen this issue before.

When using an AI model for predictions, it's possible that some panels may have zero points, which leads to the error you're encountering. This happens because the polygons for those panels don't contain any points, and as a result, the code tries to process them and raises an error.

To resolve this, you can add a condition to check if the polygon has points. If not, you can skip those labels by using a `continue` statement in the loop to move to the next annotation.
https://github.com/HumanSignal/label-studio-sdk/blob/114c2b30bd36b2ff4577abc40f05955630a59f6b/src/label_studio_sdk/converter/converter.py#L922-L927
Here’s a quick example of what that might look like:

```python
 elif "polygonlabels" in label or "polygon" in label:
     if 'points' not in label:
          continue
     points_abs = [(x / 100, y / 100) for x, y in label["points"]] 
     annotations.append( 
         [category_id] 
         + [coord for point in points_abs for coord in point] 
     ) 
```

This should prevent the error from occurring when there are polygons without points. Let me know if that works for you!

I'll make a pull request for that and will inform you!

**Comment by chen-ricky** [comment]
@rezakarbasi 
Looks fine to me. Thanks

**Comment by rezakarbasi** [comment]
@xtrementl @makseq @nick-skriabin 
Do you see any problems in what I added to the project that you haven't approved the pull-request yet?

**Comment by makseq** [comment]
The fix is merged into master!
